list(APPEND PLATFORM_REQUIRED_DEPS GBM LibDRM LibInput Xkbcommon UDEV)
list(APPEND PLATFORM_OPTIONAL_DEPS VAAPI)

if ("gl" IN_LIST APP_RENDER_SYSTEM OR "gles" IN_LIST APP_RENDER_SYSTEM)
  list(APPEND PLATFORM_REQUIRED_DEPS EGL)
endif()

if("gl" IN_LIST APP_RENDER_SYSTEM)
  list(APPEND PLATFORM_REQUIRED_DEPS OpenGl)
endif()

if("gles" IN_LIST APP_RENDER_SYSTEM)
  list(APPEND PLATFORM_REQUIRED_DEPS OpenGLES)
endif()
